export interface ATTown {
  mile: number;
  name: string;
  state: string;
  distance: string;
  notes?: string;
}

export const AT_TOWNS: ATTown[] = [
  { mile: 0, name: "Amicalola Falls SP", state: "GA", distance: "On Trail", notes: "Common NOBO start point" },
  { mile: 69, name: "Hiawassee", state: "GA", distance: "~11 mi", notes: "Hitch required" },
  { mile: 109, name: "Franklin", state: "NC", distance: "~10 mi", notes: "Via Winding Stair Gap - good medical access" },
  { mile: 137, name: "NOC", state: "NC", distance: "On Trail", notes: "Nantahala Outdoor Center - rafting!" },
  { mile: 208, name: "Gatlinburg", state: "TN", distance: "~16 mi", notes: "Via Newfound Gap - major hitch required" },
  { mile: 242, name: "Standing Bear Farm", state: "NC", distance: "~0.2 mi", notes: "Classic hiker hostel, trail history museum" },
  { mile: 344, name: "Erwin", state: "TN", distance: "~0.5 mi", notes: "Uncle Johnny's Hostel, Johnson City medical nearby" },
  { mile: 365, name: "Roan Mountain", state: "TN", distance: "~5 mi", notes: "Borderline walkable, most hitch" },
  { mile: 420, name: "Hampton", state: "TN", distance: "~1 mi", notes: "Walkable Dollar General" },
  { mile: 592, name: "Bland", state: "VA", distance: "~0.5 mi", notes: "Big Walker Motel, quiet town" },
  { mile: 517, name: "Bastian", state: "VA", distance: "~0.5 mi", notes: "Four Pines Hostel, very limited services" },
  { mile: 534, name: "Partnership Shelter", state: "VA", distance: "On Trail", notes: "Pizza delivery to shelter!" },
  { mile: 637, name: "Pearisburg", state: "VA", distance: "~0.8 mi", notes: "Walkable DG, decent resupply" },
  { mile: 705, name: "Catawba", state: "VA", distance: "~1 mi", notes: "Four Pines Hostel, The Homeplace restaurant" },
  { mile: 730, name: "Daleville", state: "VA", distance: "~0.5 mi", notes: "Good resupply, right off I-81" },
  { mile: 788, name: "Glasgow", state: "VA", distance: "~3 mi", notes: "Borderline walkable, some hitch" },
  { mile: 893, name: "Loft Mountain Wayside", state: "VA", distance: "On Trail", notes: "Seasonal, limited hours" },
  { mile: 927, name: "Big Meadows", state: "VA", distance: "On Trail", notes: "Seasonal, popular Shenandoah stop" },
  { mile: 934, name: "Skyland Resort", state: "VA", distance: "On Trail", notes: "Historic lodge in Shenandoah" },
  { mile: 972, name: "Front Royal", state: "VA", distance: "~1-3 mi", notes: "Shenandoah north exit" },
  { mile: 1105, name: "Pine Grove Furnace", state: "PA", distance: "On Trail", notes: "Half Gallon Challenge! Actual halfway point" },
  { mile: 1124, name: "Boiling Springs", state: "PA", distance: "On Trail", notes: "Beautiful town, ATC Mid-Atlantic, limited resupply" },
  { mile: 1150, name: "Duncannon", state: "PA", distance: "~0.5 mi", notes: "Doyle Hotel - \"an experience\", PA is hard on feet!" },
  { mile: 1220, name: "Port Clinton", state: "PA", distance: "~0.3 mi", notes: "2MP Hostel, pavilion camping" },
  { mile: 1261, name: "Palmerton", state: "PA", distance: "~1.5 mi", notes: "Jail hostel at church, walkable DG" },
  { mile: 1298, name: "Delaware Water Gap", state: "PA", distance: "On Trail", notes: "Church of the Mountain hostel, PA/NJ border" },
  { mile: 1349, name: "Unionville", state: "NY", distance: "~0.8 mi", notes: "Horler's General Store hostel upstairs" },
  { mile: 1374, name: "Greenwood Lake", state: "NY", distance: "~1.5 mi", notes: "Borderline walkable" },
  { mile: 1410, name: "Bear Mountain", state: "NY", distance: "~0.5 mi", notes: "Bear Mountain Inn (expensive), zoo, limited services" },
  { mile: 1473, name: "Kent", state: "CT", distance: "~1.5-2 mi", notes: "Borderline walkable" },
  { mile: 1528, name: "Great Barrington", state: "MA", distance: "~1.5 mi", notes: "Good town, walkable DG" },
  { mile: 1576, name: "Dalton", state: "MA", distance: "On Trail", notes: "Tom Levardi's legendary house (donation), trail through town" },
  { mile: 1599, name: "North Adams", state: "MA", distance: "~3 mi", notes: "Borderline walkable, most hitch" },
  { mile: 1618, name: "Bennington", state: "VT", distance: "~5 mi", notes: "Hitch required, major medical access" },
  { mile: 1658, name: "Manchester Center", state: "VT", distance: "~5 mi", notes: "Hitch required, great outfitters" },
  { mile: 1712, name: "Killington", state: "VT", distance: "~1-2 mi", notes: "Inn at Long Trail on trail, town requires ride" },
  { mile: 1755, name: "Hanover", state: "NH", distance: "On Trail", notes: "Dartmouth College town! Fix everything before Whites" },
  { mile: 1804, name: "Glencliff", state: "NH", distance: "~0.5 mi", notes: "Hikers Welcome Hostel, very limited" },
  { mile: 1822, name: "Lincoln/Woodstock", state: "NH", distance: "~5-6 mi", notes: "Last major resupply before Whites - hitch required" },
  { mile: 1832, name: "Franconia Notch", state: "NH", distance: "On Trail", notes: "Just parking area, no lodging" },
  { mile: 1869, name: "Crawford Notch", state: "NH", distance: "On Trail", notes: "Highland Center Lodge (AMC, expensive)" },
  { mile: 1888, name: "Pinkham Notch", state: "NH", distance: "On Trail", notes: "Joe Dodge Lodge (AMC base), very limited resupply" },
  { mile: 1898, name: "Gorham", state: "NH", distance: "~1.5 mi", notes: "Major resupply after Whites, Hiker's Paradise hostel" },
  { mile: 1950, name: "Andover", state: "ME", distance: "~0.8 mi", notes: "Pine Ellis Hostel, small grocery" },
  { mile: 1977, name: "Rangeley", state: "ME", distance: "~9 mi", notes: "Hitch required, major resupply" },
  { mile: 2009, name: "Stratton", state: "ME", distance: "~5 mi", notes: "Hitch required, last major before 100-Mile Wilderness" },
  { mile: 2046, name: "Caratunk", state: "ME", distance: "~0.5 mi", notes: "Near Kennebec River Ferry crossing" },
  { mile: 2133, name: "White House Landing", state: "ME", distance: "Boat Only", notes: "Mid-100-Mile Wilderness option, boat taxi, famous burger" },
  { mile: 2183, name: "Millinocket", state: "ME", distance: "~15 mi", notes: "Shuttle required, celebration town, post-finish destination" },
];
