// ============================================
// TRAIL LEGS - AMC Hut Sprites
// ============================================
// Appalachian Mountain Club huts in the White Mountains
// Iconic mountain lodges along the AT

import { PixelSprite } from './types';
import { C } from './palette';

const _ = C.transparent;

// Lakes of the Clouds Hut - largest and most famous
// Large stone and wood structure at 5,012 feet
const lakesOfTheClouds: PixelSprite = {
  name: 'lakes_of_the_clouds',
  width: 56,
  height: 36,
  pixels: [
    // Row 0-1: Sky/roof peak
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    // Row 2-3: Main roof section
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    // Row 4-5: Roof expansion
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    // Row 6-7: Wings start
    [_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_],
    // Row 8-9: Full roof span
    [_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_],
    // Row 10-11: Roof edge / wall transition
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_],
    // Row 12-15: Stone walls with windows
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    // Row 16-19: More stone wall
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    // Row 20-23: Lower wall with door
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    // Row 24-27: Foundation
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_],
    // Row 28-31: Ground/rock base
    [_,_,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_],
    // Row 32-35: Rocky terrain
    [_,_,_,_,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,C.grayDark,C.grayDark,_,_,_,_,C.grayDark,_,_,_,_,C.grayDark,C.grayDark,_,_,_,_,C.grayDark,_,_,_,_,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  ],
};

// Madison Spring Hut - Classic stone hut on exposed ridge
const madisonSpring: PixelSprite = {
  name: 'madison_spring',
  width: 40,
  height: 28,
  pixels: [
    // Row 0-3: Peaked roof
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_],
    // Row 4-7: Roof expansion
    [_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    // Row 8-11: Stone wall with windows
    [C.grayDark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.skyBlue,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    // Row 12-15: Stone wall with door
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    // Row 16-19: Lower wall and door
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_,_],
    // Row 20-23: Foundation
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,_,_,_,_,_],
    [_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_],
    // Row 24-27: Rocky ground
    [_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,C.grayDark,C.grayMedium,_,_,C.grayDark,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_],
    [_,_,_,C.grayDark,_,_,_,_,C.grayDark,_,_,_,C.grayDark,_,_,_,_,C.grayDark,_,_,_,C.grayDark,_,_,_,_,C.grayDark,_,_,_,C.grayDark,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  ],
};

// Zealand Falls Hut - Compact wooden hut near waterfall
const zealandFalls: PixelSprite = {
  name: 'zealand_falls',
  width: 32,
  height: 24,
  pixels: [
    // Row 0-3: Peaked roof with chimney
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayDark,_],
    [_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,C.grayDark,C.grayDark,_,_],
    [_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_],
    // Row 4-7: Roof expansion
    [_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_],
    // Row 7-10: Wood wall upper
    [C.grayDark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.grayDark,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.skyBlue,C.skyBlue,C.skyBlue,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.skyBlue,C.skyBlue,C.skyBlue,C.barkDark,C.bark,C.bark,C.barkDark,C.grayDark,_,_,_],
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyLight,C.skyBlue,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyLight,C.skyBlue,C.bark,C.barkDark,C.bark,C.bark,C.grayDark,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.skyBlue,C.skyBlue,C.skyBlue,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.skyBlue,C.skyBlue,C.skyBlue,C.barkDark,C.bark,C.bark,C.barkDark,C.grayDark,_,_,_],
    // Row 11-14: Wood wall lower with door
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.grayDark,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.grayDark,_,_,_],
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.barkDark,C.nearBlack,C.nearBlack,C.nearBlack,C.nearBlack,C.barkDark,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.grayDark,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.nearBlack,C.nearBlack,C.nearBlack,C.nearBlack,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.grayDark,_,_,_],
    // Row 15-17: Foundation
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.barkDark,C.nearBlack,C.nearBlack,C.nearBlack,C.nearBlack,C.barkDark,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.grayDark,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,_,_,_,_],
    // Row 18-23: Ground with waterfall hint
    [_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    [_,_,C.grayDark,C.grayMedium,_,_,C.waterBlue,C.waterBlue,C.skyLight,C.waterBlue,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayMedium,_,_,_,_,_],
    [_,_,_,_,_,_,C.waterBlue,C.skyLight,C.waterBlue,C.waterBlue,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,C.waterBlue,C.waterBlue,C.waterBlue,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  ],
};

// Greenleaf Hut - On the Franconia Ridge
const greenleaf: PixelSprite = {
  name: 'greenleaf',
  width: 36,
  height: 24,
  pixels: [
    // Row 0-3: Roof peak
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_],
    // Row 4-6: Roof expansion
    [_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_],
    // Row 7-10: Stone wall with windows
    [C.grayDark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.skyBlue,C.skyLight,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.skyBlue,C.skyLight,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.skyBlue,C.skyBlue,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_],
    // Row 11-14: Stone wall with door
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayDark,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.bark,C.bark,C.bark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_],
    // Row 15-17: Lower wall and door
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.bark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayDark,_,_,_],
    [C.grayDark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.bark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayLight,C.grayDark,_,_,_],
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_],
    // Row 18-23: Foundation and ground
    [_,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,_,_,_,_],
    [_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    [_,_,C.grayDark,C.grayMedium,_,_,C.grayDark,_,_,_,C.grayDark,C.grayMedium,_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,_,_,_,C.grayMedium,C.grayDark,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  ],
};

// Lonesome Lake Hut - Lake-side hut
const lonesomeLake: PixelSprite = {
  name: 'lonesome_lake',
  width: 32,
  height: 20,
  pixels: [
    // Row 0-3: Roof
    [_,_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_],
    // Row 4-5: Roof edge
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    // Row 5-8: Wood walls with windows
    [C.grayDark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.bark,C.grayDark,_,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyBlue,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyBlue,C.bark,C.bark,C.barkDark,C.grayDark,_,_,_,_],
    [C.grayDark,C.bark,C.barkDark,C.bark,C.skyBlue,C.skyLight,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.skyBlue,C.skyLight,C.barkDark,C.bark,C.bark,C.grayDark,_,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyBlue,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.skyBlue,C.skyBlue,C.bark,C.bark,C.barkDark,C.grayDark,_,_,_,_],
    // Row 9-12: Door
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.bark,C.grayDark,_,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.grayDark,_,_,_,_],
    [C.grayDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.nearBlack,C.nearBlack,C.nearBlack,C.nearBlack,C.barkDark,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.grayDark,_,_,_,_],
    [C.grayDark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.barkDark,C.nearBlack,C.nearBlack,C.nearBlack,C.nearBlack,C.barkDark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.bark,C.barkDark,C.bark,C.barkDark,C.grayDark,_,_,_,_],
    // Row 13-15: Foundation
    [C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,C.grayDark,C.grayMedium,_,_,_,_,_],
    [_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_],
    // Row 16-19: Lake reflection
    [_,_,_,_,_,_,_,_,_,_,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,C.waterBlue,C.waterBlue,C.skyLight,C.waterBlue,C.waterBlue,C.skyLight,C.waterBlue,C.waterBlue,C.skyLight,C.waterBlue,C.waterBlue,C.skyLight,C.waterBlue,C.waterBlue,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
  ],
};

export const AMC_HUT_SPRITES = {
  lakesOfTheClouds,
  madisonSpring,
  zealandFalls,
  greenleaf,
  lonesomeLake,
};
