// ============================================
// TRAIL LEGS - Vista and Panorama Sprites
// ============================================
// Scenic background sprites for mountain viewpoints

import { PixelSprite } from './types';
import { C } from './palette';

const _ = C.transparent;

// Blue Ridge mountain layers (parallax background)
const blueRidgeLayers: PixelSprite = {
  name: 'blue_ridge_layers',
  width: 64,
  height: 24,
  pixels: [
    // Row 0-3: Sky gradient
    [C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue],
    [C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue,C.skyBlue],
    [C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight],
    [C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight],
    // Row 4-7: Distant mountain layer (lightest blue)
    [C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight],
    [C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight],
    [C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight],
    [C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.skyLight,C.info],
    // Row 8-11: Mid-distance layer (medium blue)
    [C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info],
    [C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info],
    [C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.info,C.waterBlue],
    [C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.info,C.info,C.info,C.info,C.info,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue],
    // Row 12-15: Near mountain layer (darker blue-green)
    [C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue],
    [C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue],
    [C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep],
    [C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterBlue,C.waterBlue,C.waterBlue,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep],
    // Row 16-19: Foreground ridgeline (dark forest)
    [C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep],
    [C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark],
    [C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark],
    [C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.waterDeep,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark],
    // Row 20-23: Valley floor (green forest)
    [C.forestDark,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark],
    [C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen],
    [C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen],
    [C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen],
  ],
};

// Rock outcrop viewpoint
const rockOutcrop: PixelSprite = {
  name: 'rock_outcrop',
  width: 32,
  height: 16,
  pixels: [
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,_,_,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,_,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_,_,_,_],
    [_,_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_,_],
    [_,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_,_,_,_,_,_],
    [C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,_,_,_,_,_,_],
    [C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayLight,C.grayLight,C.grayLight,C.grayLight,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,_,_,_,_],
    [_,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,_,_,_],
    [_,_,C.grayDark,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,C.grayDark,_,_],
    [_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayMedium,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_],
    [_,_,_,_,_,_,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,C.grayDark,_,_,_,_,_,_,_,_],
  ],
};

// Forest treeline silhouette
const treeline: PixelSprite = {
  name: 'treeline',
  width: 48,
  height: 12,
  pixels: [
    [_,_,_,_,_,C.forestDark,_,_,_,_,_,_,_,C.forestDark,_,_,_,_,_,_,C.forestDark,_,_,_,_,_,_,_,_,C.forestDark,_,_,_,_,_,_,C.forestDark,_,_,_,_,_,_,C.forestDark,_,_,_,_],
    [_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_,_,C.forestDark,C.forestDark,C.forestDark,_,_,_],
    [_,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_,C.forestDark,C.forestGreen,C.forestDark,C.forestGreen,C.forestDark,_,_],
    [_,_,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,_,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,_,_,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,_],
    [_,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark,C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark],
    [C.forestDark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestDark],
    [C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen],
    [C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.bark,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen,C.forestGreen],
    [C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.bark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark,C.forestDark],
    [C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.bark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt],
    [C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.barkDark,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt],
    [C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt,C.trailDirt],
  ],
};

// Simple cloud
const cloud: PixelSprite = {
  name: 'cloud',
  width: 16,
  height: 8,
  pixels: [
    [_,_,_,_,_,C.white,C.white,C.white,C.white,_,_,_,_,_,_,_],
    [_,_,_,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,_,_,_,_,_],
    [_,_,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,_,_,_,_],
    [_,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,_,_,_],
    [C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,_,_],
    [C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,_],
    [C.grayLight,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white],
    [_,C.grayLight,C.grayLight,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.white,C.grayLight,C.grayLight,C.grayLight,_],
  ],
};

export const VISTA_SPRITES = {
  blueRidgeLayers,
  rockOutcrop,
  treeline,
  cloud,
};
