// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  workspaceId: __t.string().name("workspace_id"),
  turnId: __t.string().name("turn_id"),
  eventSeq: __t.u64().name("event_seq"),
  kind: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  createdAt: __t.string().name("created_at"),
});
