// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  trailId: __t.string(),
  source: __t.string(),
  chipText: __t.string().optional(),
  noteText: __t.string(),
  reporterTrailName: __t.string().optional(),
  snappedMile: __t.f64(),
  observedAt: __t.string().optional(),
};
