// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  trailId: __t.string().name("trail_id"),
  source: __t.string(),
  chipText: __t.string().optional().name("chip_text"),
  noteText: __t.string().name("note_text"),
  reporterTrailName: __t.string().optional().name("reporter_trail_name"),
  snappedMile: __t.f64().name("snapped_mile"),
  observedAt: __t.string().name("observed_at"),
  status: __t.string(),
  createdAt: __t.string().name("created_at"),
});
