// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BetaProfile = __t.object("BetaProfile", {
  id: __t.u64(),
  email: __t.string(),
  name: __t.string(),
  trailName: __t.string(),
  createdAt: __t.string(),
});
export type BetaProfile = __Infer<typeof BetaProfile>;

export const DadUpdate = __t.object("DadUpdate", {
  id: __t.u64(),
  title: __t.string(),
  status: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  detail: __t.string(),
  observedAt: __t.string(),
});
export type DadUpdate = __Infer<typeof DadUpdate>;

export const ManualNote = __t.object("ManualNote", {
  id: __t.u64(),
  trailName: __t.string(),
  sectionId: __t.string(),
  title: __t.string(),
  body: __t.string(),
  createdAt: __t.string(),
});
export type ManualNote = __Infer<typeof ManualNote>;

export const MyScoutTurnEvents = __t.object("MyScoutTurnEvents", {});
export type MyScoutTurnEvents = __Infer<typeof MyScoutTurnEvents>;

export const MyScoutTurns = __t.object("MyScoutTurns", {});
export type MyScoutTurns = __Infer<typeof MyScoutTurns>;

export const PublicAnnouncement = __t.object("PublicAnnouncement", {
  id: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  publishedAt: __t.string(),
});
export type PublicAnnouncement = __Infer<typeof PublicAnnouncement>;

export const TrailConditionReport = __t.object("TrailConditionReport", {
  id: __t.u64(),
  trailId: __t.string(),
  source: __t.string(),
  chipText: __t.string().optional(),
  noteText: __t.string(),
  reporterTrailName: __t.string().optional(),
  snappedMile: __t.f64(),
  observedAt: __t.string(),
  status: __t.string(),
  createdAt: __t.string(),
});
export type TrailConditionReport = __Infer<typeof TrailConditionReport>;

export const ScoutTurn = __t.object("ScoutTurn", {
  id: __t.u64(),
  workspaceId: __t.string(),
  turnId: __t.string(),
  status: __t.string(),
  thinkingEffort: __t.string(),
  startedAt: __t.string(),
  updatedAt: __t.string(),
});
export type ScoutTurn = __Infer<typeof ScoutTurn>;

export const ScoutTurnEvent = __t.object("ScoutTurnEvent", {
  id: __t.u64(),
  workspaceId: __t.string(),
  turnId: __t.string(),
  eventSeq: __t.u64(),
  kind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.string(),
});
export type ScoutTurnEvent = __Infer<typeof ScoutTurnEvent>;

export const ScoutWorkspaceAccess = __t.object("ScoutWorkspaceAccess", {
  id: __t.u64(),
  identity: __t.identity(),
  workspaceId: __t.string(),
  createdAt: __t.string(),
});
export type ScoutWorkspaceAccess = __Infer<typeof ScoutWorkspaceAccess>;

export const VideoDispatch = __t.object("VideoDispatch", {
  id: __t.u64(),
  youtubeId: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  publishedAt: __t.string(),
});
export type VideoDispatch = __Infer<typeof VideoDispatch>;
