// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BetaProfile = __t.object("BetaProfile", {
  id: __t.u64(),
  email: __t.string(),
  name: __t.string(),
  trailName: __t.string(),
  createdAt: __t.string(),
});
export type BetaProfile = __Infer<typeof BetaProfile>;

export const DadUpdate = __t.object("DadUpdate", {
  id: __t.u64(),
  title: __t.string(),
  status: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  detail: __t.string(),
  observedAt: __t.string(),
});
export type DadUpdate = __Infer<typeof DadUpdate>;

export const ManualNote = __t.object("ManualNote", {
  id: __t.u64(),
  trailName: __t.string(),
  sectionId: __t.string(),
  title: __t.string(),
  body: __t.string(),
  createdAt: __t.string(),
});
export type ManualNote = __Infer<typeof ManualNote>;

export const PublicAnnouncement = __t.object("PublicAnnouncement", {
  id: __t.u64(),
  title: __t.string(),
  body: __t.string(),
  publishedAt: __t.string(),
});
export type PublicAnnouncement = __Infer<typeof PublicAnnouncement>;

export const VideoDispatch = __t.object("VideoDispatch", {
  id: __t.u64(),
  youtubeId: __t.string(),
  title: __t.string(),
  summary: __t.string(),
  publishedAt: __t.string(),
});
export type VideoDispatch = __Infer<typeof VideoDispatch>;

