// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  trailId: __t.string().name("trail_id"),
  mile: __t.f64(),
  sourceName: __t.string().name("source_name"),
  status: __t.string(),
  reporterTrailName: __t.option(__t.string()).name("reporter_trail_name"),
  observedAt: __t.string().name("observed_at"),
  createdAt: __t.string().name("created_at"),
});
