// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AppendManualNoteReducer from "../append_manual_note_reducer";
import RegisterBetaProfileReducer from "../register_beta_profile_reducer";

export type AppendManualNoteParams = __Infer<typeof AppendManualNoteReducer>;
export type RegisterBetaProfileParams = __Infer<typeof RegisterBetaProfileReducer>;

